# Generated by Django 5.0.2 on 2024-05-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxidetails',
            old_name='regisration_number',
            new_name='registration_number',
        ),
    ]
